config/routes.rb
Rails.application.routes.draw do
  resources :historicos
  resources :advogados
  root 'advogados#index'

  get '/processos/:processo_id/historico_processo' =>'processos#historico_processo'
  get '/advogados_list' => 'advogados#list'

  devise_for :users
  resources :processos do
    resources :historicos
  end
end

app/models/advogado.rb
class Advogado < ApplicationRecord
  belongs_to :user
  has_many :processos, dependent: :destroy

  validates :nome, presence: true, length: { minimum: 3 }
  validates :n_OAB, presence: true, length: { is: 6 }
end

app/controllers/advogados_controller.rb
class AdvogadosController < ApplicationController
  before_action :set_advogado, only: [:show, :edit, :update, :destroy]

  # GET /advogados
  # GET /advogados.json
  def index
    if current_user.advogado.nil?
      redirect_to(:action => 'new')
    else
      @advogado = current_user.advogado
    end
  end

  def list
    @advogados = Advogado.all
  end

  # GET /advogados/1
  # GET /advogados/1.json
  # def show
  # end

  # GET /advogados/new
  def new
    @advogado = Advogado.new
  end

  # GET /advogados/1/edit
  def edit
  end

  # POST /advogados
  # POST /advogados.json
  def create
    @advogado = Advogado.new(advogado_params)
    @advogado.user = current_user
    respond_to do |format|
      if @advogado.save
        format.html { redirect_to @advogado, notice: 'Advogado was successfully created.' }
        format.json { render :index, status: :created, location: @advogado }
      else
        format.html { render :new }
        format.json { render json: @advogado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advogados/1
  # PATCH/PUT /advogados/1.json
  def update
    respond_to do |format|
      if @advogado.update(advogado_params)
        format.html { redirect_to @advogado, notice: 'Advogado was successfully updated.' }
        format.json { render :show, status: :ok, location: @advogado }
      else
        format.html { render :edit }
        format.json { render json: @advogado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advogados/1
  # DELETE /advogados/1.json
  def destroy
    @advogado.destroy
    respond_to do |format|
      format.html { redirect_to advogados_url, notice: 'Advogado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advogado
      @advogado = Advogado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advogado_params
      params.require(:advogado).permit(:nome, :n_OAB)
    end
end

app/helpers/advogados_helper.rb
module AdvogadosHelper
end

app/views/advogados/_form.html.erb
<%= form_with(model: advogado, local: true) do |form| %>
  <% if advogado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(advogado.errors.count, "error") %> prohibited this advogado from being saved:</h2>

      <ul>
      <% advogado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :advogado_nome %>
  </div>

  <div class="field">
    <%= form.label :n_OAB %>
    <%= form.text_field :n_OAB, id: :advogado_n_OAB %>
  </div>

  <div class="actions">
    <%= form.submit value='submit' %>
  </div>
<% end %>

app/views/advogados/_show.html.erb
<p>
  <strong>Nome:</strong>
  <%= @advogado.nome %>
</p>

<p>
  <strong>N oab:</strong>
  <%= @advogado.n_OAB %>
</p>

app/views/advogados/edit.html.erb
<h1>Editing Advogado</h1>
<hr>
<%= link_to 'Back', advogado_path(@advogado) %> |
<%= link_to 'Edit account', edit_user_registration_path %>

<%= render 'form', advogado: @advogado %>

app/views/advogados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pagina Inicial</h1>
<hr>
<%= link_to 'Processos',processos_path %> |
<%= link_to 'Advogados', advogados_list_path %> |
<%= link_to 'Show',advogado_path(@advogado) %> |
<%= link_to 'Sair',destroy_user_session_path, method: :delete %>


<%= render 'show', advogado: @advogado %>
<br>

app/views/advogados/list.html.erb
<h1>Lista de Advogados</h1>
<hr>
<%= link_to 'Back', advogados_path %>
<table>
  <thead>
  <tr>
    <th>Nome</th>
    <th>N oab</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @advogados.each do |advogado| %>
    <tr>
      <td><%= advogado.nome %></td>
      <td><%= advogado.n_OAB %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/advogados/new.html.erb
<h1>New Advogado</h1>

<%= render 'form', advogado: @advogado %>

<p><%= button_to "Cancel my account", registration_path(current_user), data: { confirm: "Are you sure?" }, method: :delete %></p>

app/views/advogados/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Advogado Info - <%=@advogado.nome %> </h1>
<hr>
<%= link_to 'Back', advogados_path %> |
<%= link_to 'Edit', edit_advogado_path(@advogado) %>

<%= render 'show' %>

<p>
  <strong>Email:</strong>
  <%= @advogado.user.email %>
</p>