config/routes.rb
Rails.application.routes.draw do
  resources :historicos
  resources :advogados
  root 'advogados#index'

  get '/processos/:processo_id/historico_processo' =>'processos#historico_processo'
  get '/advogados_list' => 'advogados#list'

  devise_for :users
  resources :processos do
    resources :historicos
  end
end

app/models/historico.rb
class Historico < ApplicationRecord
  belongs_to :processo
  validates :descricao, presence: true, length: { minimum: 5 }
end

app/controllers/historicos_controller.rb
class HistoricosController < ApplicationController
  before_action :set_historico, only: [:show, :edit, :update, :destroy]

  # GET /historicos
  # GET /historicos.json
  def index
    @processo = Processo.find(params[:processo_id])
    @historicos = @processo.historicos
  end

  # GET /historicos/1
  # GET /historicos/1.json
  def show
  end

  # GET /historicos/new
  def new
    @historico = Historico.new
  end

  # GET /historicos/1/edit
  def edit
  end

  # POST /historicos
  # POST /historicos.json
  def create
    @processo = Processo.find(params[:processo_id])
    @historico = @processo.historicos.create(historico_params)

    respond_to do |format|
      if @historico.save
        format.html { redirect_to @historico, notice: 'Historico was successfully created.' }
        format.json { render :show, status: :created, location: @historico }
      else
        format.html { redirect_to processo_historicos_url(@processo), notice: 'Unable to update history with empty description.' }
        format.json { render json: @historico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /historicos/1
  # PATCH/PUT /historicos/1.json
  def update
    respond_to do |format|
      if @historico.update(historico_params)
        format.html { redirect_to @historico, notice: 'Historico was successfully updated.' }
        format.json { render :show, status: :ok, location: @historico }
      else
        format.html { render :edit }
        format.json { render json: @historico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /historicos/1
  # DELETE /historicos/1.json
  def destroy
    @processo = @historico.processo
    @historico.destroy
    respond_to do |format|
      format.html { redirect_to processo_historicos_url(@processo), notice: 'Historico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_historico
      @historico = Historico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def historico_params
      params.require(:historico).permit(:descricao, :processo_id)
    end
end

app/helpers/historicos_helper.rb
module HistoricosHelper
end

app/views/historicos/_form.html.erb
<%= form_with(model: [@processo, @processo.historicos.build], local: true) do |form| %>
  <div class="field">
    <%= form.label :Atualizar_historico %>
    <%= form.text_field :descricao, id: :historico_descricao %>
  </div>

  <div class="actions">
    <%= form.submit value='submit' %>
  </div>
<% end %>

app/views/historicos/_historico.html.erb
<p>
  <strong>Descricao</strong>
  <%= historico.descricao %>
  <%= link_to 'Edit', edit_processo_historico_path(historico.processo, historico), id: "e-#{historico.descricao}" %>
  <%= link_to 'Destroy', [historico.processo, historico], id: "d-#{historico.descricao}", method: :delete,
                         data: {confirm: 'Are you sure?'}%>
</p>

app/views/historicos/edit.html.erb
<h1>Editing Historico</h1>

<%= form_with(model: @historico, local: true) do |form| %>
  <div class="field">
    <%= form.label :Atualizar_historico %>
    <%= form.text_field :descricao, id: :historico_descricao %>
  </div>

  <div class="actions">
    <%= form.submit valeu='submit'%>
  </div>
<% end %>

<%= link_to 'Show', @historico %> |
<%= link_to 'Back', historicos_path %>

app/views/historicos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Histórico - Processo <%= @processo.num_processo %></h1>
<hr>
<%= render @processo.historicos %>
<br>
<%= render 'historicos/form' %>
<hr>
<%= link_to 'Back', processo_path(@processo) %>

app/views/historicos/new.html.erb
<h1>New Historico</h1>

<%= render 'form', historico: @historico %>

<%= link_to 'Back', historicos_path %>

app/views/historicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @historico.descricao %>
</p>

<p>
  <strong>Processo:</strong>
  <%= link_to @historico.processo.num_processo, processo_path(@historico.processo) %>
</p>

<%= link_to 'Edit', edit_historico_path(@historico) %> |
<%= link_to 'Back', processo_historicos_path(@historico.processo) %>