config/routes.rb
Rails.application.routes.draw do
  resources :historicos
  resources :advogados
  root 'advogados#index'

  get '/processos/:processo_id/historico_processo' =>'processos#historico_processo'
  get '/advogados_list' => 'advogados#list'

  devise_for :users
  resources :processos do
    resources :historicos
  end
end

app/models/processo.rb
class Processo < ApplicationRecord
  has_many :historicos
  belongs_to :advogado

  validates :num_processo, presence: true
  validates :cliente, presence: true

  def self.search (query)
    where("num_processo like ?", "%#{query}%")
  end
  #validates :cliente, presence: true, length:  {minimum: 4}
  #validates :ex_adversa, presence: true, length:  {minimum: 5}
  #validates :natureza, presence: true, length:  {minimum: 5}
  #validates :assunto, presence: true, length:  {minimum: 5}
  #validates :tipo_acao, presence: true, length:  {minimum: 5}
  #validates :juizo, presence: true, length:  {minimum: 5}
  #validates :num_processo, presence: true, length:  {minimum: 5}
  #validates :ultima_movimentacao, presence: true, length:  {minimum: 5}
  #validates :ultimo_contato_cliente, presence: true
  #validates :contato_agendado, presence: true
  #validates :adv_principal, presence: true, length:  {minimum: 4}
  #validates :adv_assistente, presence: true, length:  {minimum: 4}
end

app/controllers/processos_controller.rb
class ProcessosController < ApplicationController
  before_action :set_processo, only: [:show, :edit, :update, :destroy, :historico_processo]

  # GET /processos
  # GET /processos.json
  def index
    if params[:search]
      @processos = current_user.advogado.processos.search(params[:search])
      if params[:search].empty?
        respond_to do |format|
          format.html { redirect_to processos_url, notice: 'Fill in the search field.' }
        end
      elsif @processos.empty?
        respond_to do |format|
          format.html { redirect_to processos_url, notice: 'Search returned no results.' }
        end
      end
    else
      @processos = current_user.advogado.processos
    end
  end

  # GET /processos/1
  # GET /processos/1.json
  def show
  end

  # GET /processos/new
  def new
    @processo = Processo.new
  end

  # GET /processos/1/edit
  def edit
  end

  # POST /processos
  # POST /processos.json
  def create
    @processo = Processo.new(processo_params)
    @processo.advogado = current_user.advogado

    respond_to do |format|
      if @processo.save
        format.html { redirect_to @processo, notice: 'Processo was successfully created.' }
        format.json { render :show, status: :created, location: @processo }
      else
        format.html { render :new }
        format.json { render json: @processo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /processos/1
  # PATCH/PUT /processos/1.json
  def update
    respond_to do |format|
      if @processo.update(processo_params)
        format.html { redirect_to @processo, notice: 'Processo was successfully updated.' }
        format.json { render :show, status: :ok, location: @processo }
      else
        format.html { render :edit }
        format.json { render json: @processo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /processos/1
  # DELETE /processos/1.json
  def destroy
    @processo.destroy
    respond_to do |format|
      format.html { redirect_to processos_url, notice: 'Processo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def historico_processo
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_processo
      @processo = Processo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def processo_params
      params.require(:processo).permit(:cliente, :ex_adversa, :natureza, :assunto, :tipo_acao, :juizo,
                                       :num_processo, :ultimo_contato_cliente, :contato_agendado)
    end
end

app/helpers/processos_helper.rb
module ProcessosHelper
end

app/views/processos/_form.html.erb
<%= form_with(model: processo, local: true) do |form| %>
  <% if processo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(processo.errors.count, "error") %> prohibited this processo from being saved:</h2>

      <ul>
      <% processo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cliente %>
    <%= form.text_field :cliente, id: :processo_cliente %>
  </div>

  <div class="field">
    <%= form.label :ex_adversa %>
    <%= form.text_field :ex_adversa, id: :processo_ex_adversa %>
  </div>

  <div class="field">
    <%= form.label :natureza %>
    <%= form.text_field :natureza, id: :processo_natureza %>
  </div>

  <div class="field">
    <%= form.label :assunto %>
    <%= form.text_field :assunto, id: :processo_assunto %>
  </div>

  <div class="field">
    <%= form.label :tipo_acao %>
    <%= form.text_field :tipo_acao, id: :processo_tipo_acao %>
  </div>

  <div class="field">
    <%= form.label :juizo %>
    <%= form.text_field :juizo, id: :processo_juizo %>
  </div>

  <div class="field">
    <%= form.label :num_processo %>
    <%= form.text_field :num_processo, id: :processo_num_processo %>
  </div>

  <div class="field">
    <%= form.label :ultimo_contato_cliente %>
    <%= form.date_select :ultimo_contato_cliente, id: :processo_ultimo_contato_cliente %>
  </div>

  <div class="field">
    <%= form.label :contato_agendado %>
    <%= form.date_select :contato_agendado, id: :processo_contato_agendado %>
  </div>

  <div class="actions">
    <%= form.submit value='submit'%>
  </div>
<% end %>

app/views/processos/edit.html.erb
<h1>Editing Processo</h1>

<%= render 'form', processo: @processo %>

<%= link_to 'Show', @processo %> |
<%= link_to 'Back', processos_path %>

app/views/processos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Processos</h1>
<hr>
<%= link_to "Voltar", advogados_path %>
<br>
<br>
<%= form_tag(processos_path, :method => :get) do %>
  <%=text_field_tag 'search', nil, placeholder: 'Nº do processo' %>
  <%=submit_tag "Buscar" %>
<%end %>
<br>

<table>
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Numero do processo</th>
    </tr>
  </thead>

  <tbody>
    <% @processos.each do |processo| %>
      <tr>
        <td><%= processo.cliente %></td>
        <td><%= processo.num_processo %></td>
        <td><%= link_to 'Show', processo, id: "s-#{processo.num_processo}" %></td>
        <td><%= link_to 'Edit', edit_processo_path(processo), id: "e-#{processo.num_processo}" %></td>
        <td><%= link_to 'Destroy', processo, id: "d-#{processo.num_processo}" ,method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Processo', new_processo_path %>

app/views/processos/new.html.erb
<h1>New Processo</h1>

<%= render 'form', processo: @processo %>

<%= link_to 'Back', processos_path %>

app/views/processos/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Processo - <%= @processo.num_processo %></h1>
<hr>

<p>
  <strong>Cliente:</strong>
  <%= @processo.cliente %>
</p>

<p>
  <strong>Ex adversa:</strong>
  <%= @processo.ex_adversa %>
</p>

<p>
  <strong>Natureza:</strong>
  <%= @processo.natureza %>
</p>

<p>
  <strong>Assunto:</strong>
  <%= @processo.assunto %>
</p>

<p>
  <strong>Tipo acao:</strong>
  <%= @processo.tipo_acao %>
</p>

<p>
  <strong>Juizo:</strong>
  <%= @processo.juizo %>
</p>

<p>
  <strong>Num processo:</strong>
  <%= @processo.num_processo %>
</p>

<p>
  <strong>Ultima movimentacao:</strong>
  <%if !@processo.historicos.empty? %>
    <%= @processo.historicos.last.descricao %>
  <% end %>
</p>

<p>
  <strong>Ultimo contato cliente:</strong>
  <%= @processo.ultimo_contato_cliente %>
</p>

<p>
  <strong>Contato agendado:</strong>
  <%= @processo.contato_agendado %>
</p>

<p>
  <strong>Advogado:</strong>
  <%= @processo.advogado.nome%>
</p>

<hr>

<%= link_to 'Historico', processo_historicos_path(@processo), id: "historico" %> |
<%= link_to 'Edit', edit_processo_path(@processo), id: "edit" %> |
<%= link_to 'Back', processos_path %>